package cn.edu.xmu.order.model.po;

import java.time.LocalDateTime;

public class RefundPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.payment_id
     *
     * @mbg.generated
     */
    private Long paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.pay_sn
     *
     * @mbg.generated
     */
    private String paySn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.order_id
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.gmt_created
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.aftersale_id
     *
     * @mbg.generated
     */
    private Long aftersaleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.id
     *
     * @return the value of refund.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.id
     *
     * @param id the value for refund.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.payment_id
     *
     * @return the value of refund.payment_id
     *
     * @mbg.generated
     */
    public Long getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.payment_id
     *
     * @param paymentId the value for refund.payment_id
     *
     * @mbg.generated
     */
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.amount
     *
     * @return the value of refund.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.amount
     *
     * @param amount the value for refund.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.pay_sn
     *
     * @return the value of refund.pay_sn
     *
     * @mbg.generated
     */
    public String getPaySn() {
        return paySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.pay_sn
     *
     * @param paySn the value for refund.pay_sn
     *
     * @mbg.generated
     */
    public void setPaySn(String paySn) {
        this.paySn = paySn == null ? null : paySn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.order_id
     *
     * @return the value of refund.order_id
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.order_id
     *
     * @param orderId the value for refund.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.state
     *
     * @return the value of refund.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.state
     *
     * @param state the value for refund.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.gmt_created
     *
     * @return the value of refund.gmt_created
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.gmt_created
     *
     * @param gmtCreated the value for refund.gmt_created
     *
     * @mbg.generated
     */
    public void setGmtCreated(LocalDateTime gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.gmt_modified
     *
     * @return the value of refund.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.gmt_modified
     *
     * @param gmtModified the value for refund.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.aftersale_id
     *
     * @return the value of refund.aftersale_id
     *
     * @mbg.generated
     */
    public Long getAftersaleId() {
        return aftersaleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.aftersale_id
     *
     * @param aftersaleId the value for refund.aftersale_id
     *
     * @mbg.generated
     */
    public void setAftersaleId(Long aftersaleId) {
        this.aftersaleId = aftersaleId;
    }
}