package cn.edu.xmu.freight.model.po;

import java.time.LocalDateTime;

public class PieceFreightModelPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.freight_model_id
     *
     * @mbg.generated
     */
    private Long freightModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.first_items
     *
     * @mbg.generated
     */
    private Integer firstItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.first_items_price
     *
     * @mbg.generated
     */
    private Long firstItemsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.additional_items
     *
     * @mbg.generated
     */
    private Integer additionalItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.additional_items_price
     *
     * @mbg.generated
     */
    private Long additionalItemsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.region_id
     *
     * @mbg.generated
     */
    private Long regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column piece_freight_model.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.id
     *
     * @return the value of piece_freight_model.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.id
     *
     * @param id the value for piece_freight_model.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.freight_model_id
     *
     * @return the value of piece_freight_model.freight_model_id
     *
     * @mbg.generated
     */
    public Long getFreightModelId() {
        return freightModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.freight_model_id
     *
     * @param freightModelId the value for piece_freight_model.freight_model_id
     *
     * @mbg.generated
     */
    public void setFreightModelId(Long freightModelId) {
        this.freightModelId = freightModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.first_items
     *
     * @return the value of piece_freight_model.first_items
     *
     * @mbg.generated
     */
    public Integer getFirstItems() {
        return firstItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.first_items
     *
     * @param firstItems the value for piece_freight_model.first_items
     *
     * @mbg.generated
     */
    public void setFirstItems(Integer firstItems) {
        this.firstItems = firstItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.first_items_price
     *
     * @return the value of piece_freight_model.first_items_price
     *
     * @mbg.generated
     */
    public Long getFirstItemsPrice() {
        return firstItemsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.first_items_price
     *
     * @param firstItemsPrice the value for piece_freight_model.first_items_price
     *
     * @mbg.generated
     */
    public void setFirstItemsPrice(Long firstItemsPrice) {
        this.firstItemsPrice = firstItemsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.additional_items
     *
     * @return the value of piece_freight_model.additional_items
     *
     * @mbg.generated
     */
    public Integer getAdditionalItems() {
        return additionalItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.additional_items
     *
     * @param additionalItems the value for piece_freight_model.additional_items
     *
     * @mbg.generated
     */
    public void setAdditionalItems(Integer additionalItems) {
        this.additionalItems = additionalItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.additional_items_price
     *
     * @return the value of piece_freight_model.additional_items_price
     *
     * @mbg.generated
     */
    public Long getAdditionalItemsPrice() {
        return additionalItemsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.additional_items_price
     *
     * @param additionalItemsPrice the value for piece_freight_model.additional_items_price
     *
     * @mbg.generated
     */
    public void setAdditionalItemsPrice(Long additionalItemsPrice) {
        this.additionalItemsPrice = additionalItemsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.region_id
     *
     * @return the value of piece_freight_model.region_id
     *
     * @mbg.generated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.region_id
     *
     * @param regionId the value for piece_freight_model.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.gmt_create
     *
     * @return the value of piece_freight_model.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.gmt_create
     *
     * @param gmtCreate the value for piece_freight_model.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column piece_freight_model.gmt_modified
     *
     * @return the value of piece_freight_model.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column piece_freight_model.gmt_modified
     *
     * @param gmtModified the value for piece_freight_model.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}