package cn.edu.xmu.freight.model.po;

import java.time.LocalDateTime;

public class WeightFreightModelPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.freight_model_id
     *
     * @mbg.generated
     */
    private Long freightModelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.first_weight
     *
     * @mbg.generated
     */
    private Long firstWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.first_weight_freight
     *
     * @mbg.generated
     */
    private Long firstWeightFreight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.ten_price
     *
     * @mbg.generated
     */
    private Long tenPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.fifty_price
     *
     * @mbg.generated
     */
    private Long fiftyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.hundred_price
     *
     * @mbg.generated
     */
    private Long hundredPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.trihun_price
     *
     * @mbg.generated
     */
    private Long trihunPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.above_price
     *
     * @mbg.generated
     */
    private Long abovePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.region_id
     *
     * @mbg.generated
     */
    private Long regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.gmt_create
     *
     * @mbg.generated
     */
    private LocalDateTime gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight_freight_model.gmt_modified
     *
     * @mbg.generated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.id
     *
     * @return the value of weight_freight_model.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.id
     *
     * @param id the value for weight_freight_model.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.freight_model_id
     *
     * @return the value of weight_freight_model.freight_model_id
     *
     * @mbg.generated
     */
    public Long getFreightModelId() {
        return freightModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.freight_model_id
     *
     * @param freightModelId the value for weight_freight_model.freight_model_id
     *
     * @mbg.generated
     */
    public void setFreightModelId(Long freightModelId) {
        this.freightModelId = freightModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.first_weight
     *
     * @return the value of weight_freight_model.first_weight
     *
     * @mbg.generated
     */
    public Long getFirstWeight() {
        return firstWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.first_weight
     *
     * @param firstWeight the value for weight_freight_model.first_weight
     *
     * @mbg.generated
     */
    public void setFirstWeight(Long firstWeight) {
        this.firstWeight = firstWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.first_weight_freight
     *
     * @return the value of weight_freight_model.first_weight_freight
     *
     * @mbg.generated
     */
    public Long getFirstWeightFreight() {
        return firstWeightFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.first_weight_freight
     *
     * @param firstWeightFreight the value for weight_freight_model.first_weight_freight
     *
     * @mbg.generated
     */
    public void setFirstWeightFreight(Long firstWeightFreight) {
        this.firstWeightFreight = firstWeightFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.ten_price
     *
     * @return the value of weight_freight_model.ten_price
     *
     * @mbg.generated
     */
    public Long getTenPrice() {
        return tenPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.ten_price
     *
     * @param tenPrice the value for weight_freight_model.ten_price
     *
     * @mbg.generated
     */
    public void setTenPrice(Long tenPrice) {
        this.tenPrice = tenPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.fifty_price
     *
     * @return the value of weight_freight_model.fifty_price
     *
     * @mbg.generated
     */
    public Long getFiftyPrice() {
        return fiftyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.fifty_price
     *
     * @param fiftyPrice the value for weight_freight_model.fifty_price
     *
     * @mbg.generated
     */
    public void setFiftyPrice(Long fiftyPrice) {
        this.fiftyPrice = fiftyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.hundred_price
     *
     * @return the value of weight_freight_model.hundred_price
     *
     * @mbg.generated
     */
    public Long getHundredPrice() {
        return hundredPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.hundred_price
     *
     * @param hundredPrice the value for weight_freight_model.hundred_price
     *
     * @mbg.generated
     */
    public void setHundredPrice(Long hundredPrice) {
        this.hundredPrice = hundredPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.trihun_price
     *
     * @return the value of weight_freight_model.trihun_price
     *
     * @mbg.generated
     */
    public Long getTrihunPrice() {
        return trihunPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.trihun_price
     *
     * @param trihunPrice the value for weight_freight_model.trihun_price
     *
     * @mbg.generated
     */
    public void setTrihunPrice(Long trihunPrice) {
        this.trihunPrice = trihunPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.above_price
     *
     * @return the value of weight_freight_model.above_price
     *
     * @mbg.generated
     */
    public Long getAbovePrice() {
        return abovePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.above_price
     *
     * @param abovePrice the value for weight_freight_model.above_price
     *
     * @mbg.generated
     */
    public void setAbovePrice(Long abovePrice) {
        this.abovePrice = abovePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.region_id
     *
     * @return the value of weight_freight_model.region_id
     *
     * @mbg.generated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.region_id
     *
     * @param regionId the value for weight_freight_model.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.gmt_create
     *
     * @return the value of weight_freight_model.gmt_create
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.gmt_create
     *
     * @param gmtCreate the value for weight_freight_model.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight_freight_model.gmt_modified
     *
     * @return the value of weight_freight_model.gmt_modified
     *
     * @mbg.generated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight_freight_model.gmt_modified
     *
     * @param gmtModified the value for weight_freight_model.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}