package cn.edu.xmu.ordermodule.model.po;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class PaymentPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_id
     *
     * @mbg.generated
     */
    private Short paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.customer_id
     *
     * @mbg.generated
     */
    private Short customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.staff_id
     *
     * @mbg.generated
     */
    private Byte staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.rental_id
     *
     * @mbg.generated
     */
    private Integer rentalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_date
     *
     * @mbg.generated
     */
    private LocalDateTime paymentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.last_update
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_id
     *
     * @return the value of payment.payment_id
     *
     * @mbg.generated
     */
    public Short getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_id
     *
     * @param paymentId the value for payment.payment_id
     *
     * @mbg.generated
     */
    public void setPaymentId(Short paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.customer_id
     *
     * @return the value of payment.customer_id
     *
     * @mbg.generated
     */
    public Short getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.customer_id
     *
     * @param customerId the value for payment.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Short customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.staff_id
     *
     * @return the value of payment.staff_id
     *
     * @mbg.generated
     */
    public Byte getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.staff_id
     *
     * @param staffId the value for payment.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Byte staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.rental_id
     *
     * @return the value of payment.rental_id
     *
     * @mbg.generated
     */
    public Integer getRentalId() {
        return rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.rental_id
     *
     * @param rentalId the value for payment.rental_id
     *
     * @mbg.generated
     */
    public void setRentalId(Integer rentalId) {
        this.rentalId = rentalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.amount
     *
     * @return the value of payment.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.amount
     *
     * @param amount the value for payment.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_date
     *
     * @return the value of payment.payment_date
     *
     * @mbg.generated
     */
    public LocalDateTime getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_date
     *
     * @param paymentDate the value for payment.payment_date
     *
     * @mbg.generated
     */
    public void setPaymentDate(LocalDateTime paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.last_update
     *
     * @return the value of payment.last_update
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.last_update
     *
     * @param lastUpdate the value for payment.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}